### ISSUE TITLE
default ubuntu image in @orb.yml isn't being used

### ISSUE THREAD

**Issue by aaron-dernley** [buildpacks/pack-orb#56]
Hey there,
 
 We've noticed an issue in using the orb whereby the default image in the @orb.yml file isn't being used when using the latest version of buildpacks/build job (tested in 0.29.0). This is an example of the output we see when running the following code:
 
 CircleCI error - `This job was rejected because the image 'ubuntu-2004:202010-01' is [unavailable](https://discuss.circleci.com/t/linux-image-deprecations-and-eol-for-2024/)`

Code (sensitive info removed and replaced with xxx):

```
      - buildpacks/build:
          requires:
            - unit-tests
            - integration-tests
            - mutation-tests
            - contract-provider-tests
            - snyk-scan
            - sonar-quality-scan
          version: 0.29.0
          image-file: xxx.tgz
          image-name: xxx
          builder: "xxx.jfrog.io/xxx/xxx/rhel-ubi-java"
          env-vars: xxx
          context:
            - xxx

```

Bumping the version of the job to 0.29.0 still seemed to use ubuntu-2004:202010-01 by default rather than the newer image that is not deprecated and is set to the default here https://github.com/buildpacks/pack-orb/blob/main/src/%40orb.yml#L51. An executor-image property needed to be set to ensure that the newer image was being used, so a workaround is possible.
