### ISSUE TITLE
Allow passing env vars to pack

### ISSUE THREAD

**Issue by jkutner** [buildpacks/pack-orb#6]
The orb should allow a user to pass an env var that gets set during `pack build` with the the `--env` option.

Most env vars can be set using `project.toml`, but this option is necessary for secrets.

**Comment by jkutner** [comment]
Here's some [docs for `project.toml`](https://buildpacks.io/docs/reference/config/project-descriptor/)

**Comment by karuppiah7890** [comment]
@jkutner thanks! How does the solution for this issue look like? The `--env` can be set many times https://buildpacks.io/docs/app-developer-guide/environment-variables/ , so, do we want something like

```yaml
version: 2.1
orbs:
  buildpacks: buildpacks/pack@x.y.z
workflows:
  main:
    jobs:
      - buildpacks/build:
          image-name: myimage
          builder: 'heroku/buildpacks:18'
          buildpack: heroku/ruby
          env:
          - name: BLAH_ENV
          - name: BLOO_ENV
             value: bluebloo
```

**Comment by elbandito** [comment]
@karuppiah7890 some hacks that people are doing is passing in a `string` type with comma separated values e.g. `"value1,value2,value2"` then they parse the string into separate values for the the command line.  I'm not saying this is what we should do, but I'm expecting some kind of hack will be required.   I'll do some more digging around and get back shortly.

**Comment by karuppiah7890** [comment]
Ah okay. 👍

**Comment by elbandito** [comment]
@karuppiah7890 I haven't cut an official release yet, but if you're interested, you can try it out beforehand by using the following orb version: `buildpacks/pack@dev:c5a9c18`

Example `config.yml`
```
version: 2.1
orbs:
  buildpacks: buildpacks/pack@dev:c5a9c18
workflows:
  main:
    jobs:
      - buildpacks/build:
          image-name: nodefun
          builder: cnbs/sample-builder:alpine
          buildpack: buildpacks/hello-world
          env-vars: FOO=BAR;NAME=bilbo;COLOR=red and green;URL=https://www.google.com
```

Let me know if you have any questions.
